version: '3.8'

services:
  teddy:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db
      - rabbitmq
    networks:
      - public
    environment:
      WSRS_DATABASE_USER: ${WSRS_DATABASE_USER}
      WSRS_DATABASE_PASSWORD: ${WSRS_DATABASE_PASSWORD}
      WSRS_DATABASE_NAME: ${WSRS_DATABASE_NAME}
      WSRS_DATABASE_PORT: 5432
      WSRS_DATABASE_HOST: 'db'
      RABBIT_MQ_HOST: 'amqp://rabbitmq'
      JWT_SECRET: "123456"
      URL_PUBLIC: http://localhost:8080/shortened/link
  influxdb:
    image: influxdb:1.8
    networks:
      - public
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
  grafana:
    image: grafana/grafana:9.3.8
    networks:
      - public
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${WSRS_DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${WSRS_DATABASE_USER}
      POSTGRES_PASSWORD: ${WSRS_DATABASE_PASSWORD}
      POSTGRES_DB: ${WSRS_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - public
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123
    volumes:
      - pgadmin:/var/lib/pgadmin
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - public

volumes:
  db:
  pgadmin:

networks:
  public:
    driver: bridge
