name: Continuos Integration

on: pull_request

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: v20.12.x
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Verify Docker installation
        run: docker --version

      - name: Install dependencies
        run: npm install

      - name: Build and test
        run: |
          npm run test
